api_root_path: ''
auto_reload: false
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
cors_exposed_headers: null
db_name: timelogdb
docs_url: /docs
generate_correlation_id: true
host: 127.0.0.1
mongo_dsn: '**********'
mongo_timeout: 300
openapi_url: /openapi.json
port: 8080
service_name: timelog
workers: 1
