[project]
# please adapt to package name
name = "timelog"
version = "0.1.0"
description = "Timelog - Logs time intervals"
dependencies = [
    "typer >= 0.19.1",
    "ghga-service-commons[api] >= 5.0",
    "hexkit[mongodb] >= 6.0",
]

[project.urls]
Repository = "https://github.com/thebyronhimes/timelog"

[project.scripts]
timelog = "timelog.__main__:run"
